---
- name: check DNS entries
  hosts: localhost
  tasks:
     - name: check all the dns entries
       shell: cat /etc/resolv.conf
       register: entry
       delegate_to: localhost      
       
     - name: fetch nginx access log
       copy:
          content: "{{ entry.stdout_lines}}"
          dest: /tmp/dns.txt
          remote_src: yes
       delegate_to: localhost
       
     - name: check all the dns entries
       shell: cat /tmp/dns.txt       
#       delegate_to: localhost
       
     - name: Delete content & directory
       file:
         state: absent
         path: /opt/dns.txt



