---
- name: check DNS entries
  hosts: localhost
  tasks:
     - name: check all the dns entries
       shell: cat /etc/resolv.conf >> /tmp/dns1.txt
       
     - name: fetch nginx access log
       fetch:
          src: /tmp
          dest: /tmp/dns1.txt
          flat: yes
       delegate_to: localhost


