---
- name: check DNS entries
  hosts: localhost
  tasks:
     - name: check all the dns entries
       shell: cat /etc/resolv.conf >> /tmp/dns.txt
       
     - name: fetch nginx access log
       fetch:
          src: /tmp/dns.txt
          dest: /tmp
       delegate_to: localhost

