---
- name: check DNS entries
  hosts: localhost
  tasks:
     - name: check all the dns entries
       shell: cat /etc/resolv.conf
       
     - name: Email notification
       mail:
          host: mail.sandeshonline.in
          port: 25
          sender: juhi@silvereye.co
          to: juhi@silvereye.co
          subject: "Test Email"
          body: "Test Email"
       delegate_to: localhost
