---
- name: check DNS entries
  hosts: localhost
  tasks:
     - name: check all the dns entries
       shell: cat /etc/resolv.conf >> /opt/dns.txt

     - name: fetch nginx access log
       fetch:
          src: /opt/dns.txt
          dest: /tmp/
          flat: yes
       delegate_to: localhost

     - name: Delete content & directory
       file:
         state: absent
         path: /opt/dns.txt



